"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const activity_1 = require("./activity");
const auth_1 = require("./auth");
const users_1 = require("./users");
const verifications_1 = require("./verifications");
const webhooks_1 = require("./webhooks");
const contests_1 = require("./contests");
const invites_1 = require("./invites");
const stats_1 = require("./stats");
const registration_1 = require("./registration");
const chatbot_1 = require("./chatbot");
const beta_1 = require("./beta");
const admin_1 = require("./admin");
const router = (0, express_1.Router)();
// Activity routes
router.use("/activity", activity_1.activityRouter);
router.use("/auth", auth_1.authRouter);
router.use("/users", users_1.usersRouter);
router.use("/verifications", verifications_1.verificationRouter);
router.use("/webhooks", webhooks_1.webhookRouter);
router.use("/contests", contests_1.contestRouter);
router.use("/invites", invites_1.inviteRouter);
router.use("/stats", stats_1.statsRouter);
router.use("/registration", registration_1.registrationRouter);
router.use("/chat", chatbot_1.chatbotRouter);
router.use("/beta", beta_1.betaRouter);
router.use("/admin", admin_1.adminRouter);
exports.default = router;
