// ecosystem.config.js
const path = require("path");
require("dotenv").config({
  path: path.join(__dirname, "server", ".env.local"),
});

module.exports = {
  apps: [
    {
      name: "soless-ai",
      script: "src/server.js",
      cwd: "/home/ubuntu/ai-engine",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
        GITHUB_TOKEN: process.env.GITHUB_TOKEN,
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
    },
    {
      name: "soless-server",
      script: "dist/index.js",
      cwd: "/home/ubuntu/soless-presale-site/server",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        HOST: "0.0.0.0",
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
        TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
        DISCORD_BOT_TOKEN: process.env.DISCORD_BOT_TOKEN,
        TWITTER_API_KEY: process.env.TWITTER_API_KEY,
        TWITTER_API_SECRET: process.env.TWITTER_API_SECRET,
        TWITTER_ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN,
        TWITTER_ACCESS_SECRET: process.env.TWITTER_ACCESS_SECRET,
        YOUTUBE_API_KEY: process.env.YOUTUBE_API_KEY,
        VITE_FRONTEND_URL: process.env.VITE_FRONTEND_URL,
        AI_ENGINE_URL: "http://localhost:3000",
      },
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
    },
    {
      name: "soless-worker",
      script: "dist/worker.js",
      cwd: "/home/ubuntu/soless-presale-site/server",
      env: {
        NODE_ENV: "production",
        DATABASE_URL: process.env.DATABASE_URL,
        REDIS_URL: process.env.REDIS_URL,
        ENABLE_ARCHIVING: process.env.ENABLE_ARCHIVING || "false",
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
    },
    {
      name: "soless-bot",
      script: "dist/core/bots/index.js",
      cwd: "/home/ubuntu/soless-presale-site/server",
      env: {
        NODE_ENV: "production",
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
        TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
        DISCORD_BOT_TOKEN: process.env.DISCORD_BOT_TOKEN,
        DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
        DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
        DISCORD_GUILD_ID: process.env.DISCORD_GUILD_ID,
        TWITTER_API_KEY: process.env.TWITTER_API_KEY,
        TWITTER_API_SECRET: process.env.TWITTER_API_SECRET,
        TWITTER_ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN,
        TWITTER_ACCESS_SECRET: process.env.TWITTER_ACCESS_SECRET,
        YOUTUBE_API_KEY: process.env.YOUTUBE_API_KEY,
        VITE_FRONTEND_URL: process.env.VITE_FRONTEND_URL,
        API_BASE_URL: process.env.API_BASE_URL,
        REDIS_URL: process.env.REDIS_URL,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
    },
    {
      name: "soless-website",
      script: "npx",
      args: "serve -s dist -l 4173",
      cwd: "/home/ubuntu/soless-presale-site/app",
      env: {
        NODE_ENV: "production",
        PORT: 4173,
        VITE_API_URL: "https://soless.app/api",
      },
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
  ],
};
