# SOLess Unified Platform - Subdomain Deployment Configuration

version: "3.8"

# Main Hub Configuration
main_hub:
  domain: soless.app
  port: 3000
  description: "Central hub, dashboard, and platform launcher"
  services:
    - engagement_contest
    - user_onboarding
    - cross_platform_analytics
    - platform_launcher
    - documentation_gateway

# Platform Subdomains
platforms:
  solspace:
    domain: solspace.soless.app
    port: 3001
    source: /home/scotianog/the-soless-system/solspace
    description: "Social platform for viral content and NFT minting"

  swap:
    domain: swap.soless.app
    port: 3002
    source: /home/scotianog/the-soless-system/soless-swap
    description: "Token-2022 AMM with burn mechanisms"

  solarium:
    domain: solarium.soless.app
    port: 3003
    source: /home/scotianog/the-soless-system/solarium
    description: "NFT marketplace with vault features"

# Service Subdomains
services:
  ai_engine:
    domain: ai.soless.app
    port: 3010
    source: /home/scotianog/ai-engine
    description: "AI chatbot engine (Soulie)"

  auth_service:
    domain: auth.soless.app
    port: 3011
    description: "Unified authentication service"

  api_gateway:
    domain: api.soless.app
    port: 3012
    description: "Unified API gateway and routing"

  analytics_hub:
    domain: analytics.soless.app
    port: 3013
    description: "Cross-platform analytics dashboard"

  contest_engine:
    domain: contests.soless.app
    port: 3014
    description: "Contest management and leaderboards"

  documentation:
    domain: docs.soless.app
    port: 3015
    description: "Documentation portal and tutorials"

# Nginx Configuration Template
nginx_config: |
  # Main Hub
  server {
      server_name soless.app;
      location / {
          proxy_pass http://localhost:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
  }

  # Platform Subdomains
  server {
      server_name solspace.soless.app;
      location / {
          proxy_pass http://localhost:3001;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
      }
  }

  server {
      server_name swap.soless.app;
      location / {
          proxy_pass http://localhost:3002;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
      }
  }

  server {
      server_name solarium.soless.app;
      location / {
          proxy_pass http://localhost:3003;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
      }
  }

  # Service Subdomains
  server {
      server_name ai.soless.app;
      location / {
          proxy_pass http://localhost:3010;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
      }
  }

  server {
      server_name auth.soless.app;
      location / {
          proxy_pass http://localhost:3011;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
      }
  }

  server {
      server_name api.soless.app;
      location / {
          proxy_pass http://localhost:3012;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
      }
  }

# Environment Variables Template
environment_variables: |
  # Main Hub
  MAIN_HUB_URL=https://soless.app

  # Platform URLs
  SOLSPACE_URL=https://solspace.soless.app
  SWAP_URL=https://swap.soless.app
  SOLARIUM_URL=https://solarium.soless.app

  # Service URLs
  AI_ENGINE_URL=https://ai.soless.app
  AUTH_SERVICE_URL=https://auth.soless.app
  API_GATEWAY_URL=https://api.soless.app
  ANALYTICS_URL=https://analytics.soless.app
  CONTESTS_URL=https://contests.soless.app
  DOCS_URL=https://docs.soless.app

  # Cross-Platform Configuration
  CROSS_PLATFORM_ENABLED=true
  UNIFIED_AUTH_ENABLED=true
  SHARED_JWT_SECRET=your-secure-jwt-secret-here

  # Development/Production Toggle
  NODE_ENV=production
  SUBDOMAIN_ARCHITECTURE=true

# SSL Configuration
ssl_domains:
  - soless.app
  - "*.soless.app" # Wildcard for all subdomains

# DNS Records Required
dns_records:
  - type: A
    name: "@"
    value: "YOUR_SERVER_IP"
  - type: A
    name: "solspace"
    value: "YOUR_SERVER_IP"
  - type: A
    name: "swap"
    value: "YOUR_SERVER_IP"
  - type: A
    name: "solarium"
    value: "YOUR_SERVER_IP"
  - type: A
    name: "ai"
    value: "YOUR_SERVER_IP"
  - type: A
    name: "auth"
    value: "YOUR_SERVER_IP"
  - type: A
    name: "api"
    value: "YOUR_SERVER_IP"
  - type: A
    name: "analytics"
    value: "YOUR_SERVER_IP"
  - type: A
    name: "contests"
    value: "YOUR_SERVER_IP"
  - type: A
    name: "docs"
    value: "YOUR_SERVER_IP"

# Deployment Script Template
deployment_commands: |
  #!/bin/bash
  # SOLess Unified Platform Deployment Script

  echo "🚀 Deploying SOLess Unified Platform with Subdomain Architecture"

  # Update DNS (manual step - configure with your DNS provider)
  echo "📡 Please configure DNS records as specified in this config"

  # Install dependencies
  echo "📦 Installing dependencies..."
  # Add specific installation commands here

  # Configure Nginx
  echo "⚙️ Configuring Nginx..."
  sudo cp nginx-soless-unified.conf /etc/nginx/sites-available/
  sudo ln -s /etc/nginx/sites-available/nginx-soless-unified.conf /etc/nginx/sites-enabled/

  # Setup SSL
  echo "🔒 Setting up SSL certificates..."
  sudo certbot --nginx -d soless.app -d "*.soless.app"

  # Start services
  echo "🏁 Starting all services..."
  pm2 start ecosystem.config.js

  # Restart Nginx
  sudo nginx -t && sudo systemctl reload nginx

  echo "✅ Deployment complete!"
  echo "🌐 Access your unified platform at https://soless.app"
